const express = require('express');
const healthRoutes = require('./health.routes');
const authRoutes = require('./auth.routes');
const adminRoleRoutes = require('./admin-role.routes');
const userRoutes = require('./user.routes');
const adminCompanyRoutes = require('./admin-company.routes');
const companyRoutes = require('./company.routes');
const { publicRouter: categoryRoutes, adminRouter: adminCategoryRoutes } = require('./category.routes');
const { publicRouter: productRoutes, companyRouter: companyProductRoutes } = require('./product.routes');
const companyVariantRoutes = require('./variant.routes');
const addressRoutes = require('./address.routes');
const cartRoutes = require('./cart.routes');
const orderRoutes = require('./order.routes');
const companyOrderRoutes = require('./company-order.routes');
const deliveryRoutes = require('./delivery.routes');
const adminDeliveryRoutes = require('./admin-delivery.routes');
const adminCustomerRoutes = require('./admin-customer.routes');
const adminCouponRoutes = require('./coupon.routes');
const customerCouponRoutes = require('./customer-coupon.routes');
const notificationRoutes = require('./notification.routes');
const pushTokenRoutes = require('./push-token.routes');
const { companyRouter: companyDashboardRoutes, adminRouter: adminDashboardRoutes } = require('./dashboard.routes');
const { company: companyServiceRoutes, publicRouter: servicePublicRoutes, appointment: appointmentRoutes, professional: professionalRoutes } = require('./service.routes');
const { publicRouter: popupRoutes, adminRouter: adminPopupRoutes } = require('./popup.routes');
const { publicRouter: homePromotionRoutes, adminRouter: adminHomePromotionRoutes } = require('./home-promotion.routes');
const platformSettingRoutes = require('./platform-setting.routes');
const mobileRoutes = require('./mobile.routes');
const settlementRoutes = require('./settlement.routes');
const emailTemplateRoutes = require('./email-template.routes');
const wompiRoutes = require('./wompi.routes');
const reviewRoutes = require('./review.routes');

const router = express.Router();

router.use(healthRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/admin', adminRoleRoutes);
router.use('/admin', adminCompanyRoutes);
router.use('/company', companyRoutes);
router.use('/categories', categoryRoutes);
router.use('/products', productRoutes);
router.use('/admin/categories', adminCategoryRoutes);
router.use('/company/products', companyProductRoutes);
router.use('/company/variants', companyVariantRoutes);
router.use('/customer/addresses', addressRoutes);
router.use('/cart', cartRoutes);
router.use('/orders', orderRoutes);
router.use('/', reviewRoutes.customer);
router.use('/company', reviewRoutes.company);
router.use('/admin', reviewRoutes.admin);
router.use('/company', companyOrderRoutes);
router.use('/delivery', deliveryRoutes);
router.use('/admin', adminDeliveryRoutes);
router.use('/admin', adminCustomerRoutes);
router.use('/admin/coupons', adminCouponRoutes);
router.use('/coupons', customerCouponRoutes);
router.use('/notifications', notificationRoutes);
router.use('/push-tokens', pushTokenRoutes);
router.use('/company', companyDashboardRoutes);
router.use('/admin', adminDashboardRoutes);
router.use('/company', companyServiceRoutes);
router.use('/services', servicePublicRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/professional', professionalRoutes);
router.use('/popups', popupRoutes);
router.use('/admin/popups', adminPopupRoutes);
router.use('/home-promotions', homePromotionRoutes);
router.use('/admin/home-promotions', adminHomePromotionRoutes);
router.use('/admin/platform-settings', platformSettingRoutes);
router.use('/platform-settings', platformSettingRoutes);
router.use('/admin/email-templates', emailTemplateRoutes);
router.use('/admin/platform-settings/wompi', wompiRoutes.adminRouter);
router.use('/payments/wompi', wompiRoutes.publicRouter);
router.use('/mobile', mobileRoutes);
router.use('/admin', settlementRoutes.admin);
router.use('/company', settlementRoutes.company);

module.exports = router;
